# Generated by Django 3.2 on 2021-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On the way', 'On the way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='productimg'),
        ),
    ]
