# Generated by Django 3.1.3 on 2021-05-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210511_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Cancel', 'Cancel'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
